# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '999.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(737, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Port = QtWidgets.QLabel(self.centralwidget)
        self.Port.setGeometry(QtCore.QRect(20, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Port.setFont(font)
        self.Port.setObjectName("Port")
        self.Portbox = QtWidgets.QComboBox(self.centralwidget)
        self.Portbox.setGeometry(QtCore.QRect(210, 20, 151, 31))
        self.Portbox.setObjectName("Portbox")
        self.Baudrate = QtWidgets.QLabel(self.centralwidget)
        self.Baudrate.setGeometry(QtCore.QRect(20, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Baudrate.setFont(font)
        self.Baudrate.setObjectName("Baudrate")
        self.Baudbox = QtWidgets.QComboBox(self.centralwidget)
        self.Baudbox.setGeometry(QtCore.QRect(210, 80, 151, 31))
        self.Baudbox.setObjectName("Baudbox")
        self.Baudbox.addItem("")
        self.Baudbox.addItem("")
        self.Baudbox.addItem("")
        self.Connect = QtWidgets.QPushButton(self.centralwidget)
        self.Connect.setGeometry(QtCore.QRect(390, 20, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Connect.setFont(font)
        self.Connect.setObjectName("Connect")
        self.Disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.Disconnect.setGeometry(QtCore.QRect(390, 120, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Disconnect.setFont(font)
        self.Disconnect.setObjectName("Disconnect")
        self.Input = QtWidgets.QLineEdit(self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(90, 320, 151, 41))
        self.Input.setObjectName("Input")
        self.Send = QtWidgets.QPushButton(self.centralwidget)
        self.Send.setGeometry(QtCore.QRect(70, 472, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Send.setFont(font)
        self.Send.setObjectName("Send")
        self.det = QtWidgets.QPushButton(self.centralwidget)
        self.det.setGeometry(QtCore.QRect(50, 200, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.det.setFont(font)
        self.det.setObjectName("det")
        self.state_label = QtWidgets.QLabel(self.centralwidget)
        self.state_label.setGeometry(QtCore.QRect(80, 110, 181, 41))
        self.state_label.setObjectName("state_label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(360, 250, 321, 341))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 737, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Port.setText(_translate("MainWindow", "Port"))
        self.Baudrate.setText(_translate("MainWindow", "Baudrate"))
        self.Baudbox.setItemText(0, _translate("MainWindow", "115200"))
        self.Baudbox.setItemText(1, _translate("MainWindow", "9600"))
        self.Baudbox.setItemText(2, _translate("MainWindow", "2400"))
        self.Connect.setText(_translate("MainWindow", "Connect"))
        self.Disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.Send.setText(_translate("MainWindow", "Send"))
        self.det.setText(_translate("MainWindow", "Port detection"))
        self.state_label.setText(_translate("MainWindow", "TextLabel"))
